version: "3.3"

networks:
    docker-network:
        driver: bridge

volumes:
    wp_data:
        external: false

services:
    nginx:
        build: ./requirements/nginx
        container_name: nginx
        restart: always
        hostname: ciglesia.42.fr
        domainname: ciglesia.42.fr
        ports:
            - 443:443
        networks:
            docker-network:
                aliases:
                    - ciglesia.42.fr
        volumes:
            - 'wp_data:/home/ciglesia/data/'
    wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
        networks:
            - docker-network
        volumes:
            - 'wp_data:/home/ciglesia/data/'
