version: "3.3"
services:
    nginx:
        build: ./requirements/nginx
        container_name: nginx
        restart: always
        hostname: ciglesia.42.fr
        domainname: ciglesia.42.fr
        ports:
            - 443:443
        networks:
            docker-network:
                aliases:
                    - ciglesia.42.fr
        environment:
            VERS: ${VERS}
    wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
        networks:
            - docker-network

networks:
    docker-network:
        driver: bridge
