version: "3.3"

networks:
    docker-network:
        driver: bridge

services:
    nginx:
        build: ./requirements/nginx
        image: nginx
        container_name: nginx
        depends_on:
            - wordpress
        restart: always
        hostname: $DOMAIN_NAME
        domainname: $DOMAIN_NAME
        ports:
            - 443:443
        extra_hosts:
            - "$DOMAIN_NAME:127.0.0.1"
        networks:
            docker-network:
                aliases:
                    - $DOMAIN_NAME
        volumes:
            - type: bind
              source: /home/user/data/wordpress
              target: /www/wordpress
              read_only: true
    wordpress:
        build: ./requirements/wordpress
        image: wordpress
        container_name: wordpress
        restart: always
        environment:
            - WORDPRESS_DB_HOST=mariadb:3306
            - WORDPRESS_DB_NAME=$DATABASE
            - WORDPRESS_DB_USER=$DB_USER
            - WORDPRESS_DB_PASSWORD=$DB_PASSWORD
        depends_on:
            - mariadb
        ports:
            - 9000
        networks:
            - docker-network
        volumes:
            - type: bind
              source: /home/user/data/wordpress
              target: /var/www/html/wordpress
    mariadb:
        build: ./requirements/mariadb
        image: mariadb
        container_name: mariadb
        restart: always
        env_file: .env
        ports:
            - 3306
        networks:
            - docker-network
        volumes:
            - type: bind
              source: /home/user/data/db
              target: /var/lib/mysql
